<?php

	/**
	 * Generated by the WordPress Meta Box Generator
	 * https://jeremyhixon.com/tool/wordpress-meta-box-generator/
	 *
	 * Retrieving the values:
	 * Date the email was sent = get_post_meta( get_the_ID(), 'chi_emaildate-the-email-was-sent', true )
	 * Time the email was sent = get_post_meta( get_the_ID(), 'chi_emailtime-the-email-was-sent', true )
	 * For = get_post_meta( get_the_ID(), 'chi_emailfor', true )
	 *  Notes on the text = get_post_meta( get_the_ID(), 'chi_emailnotes-on-the-text', true )
	 */
	class CHI_EMAIL_SENDER {
		private $config = '{"title":"Comments to E-mail","description":"If there are any comments on the email, please contact the author","prefix":"chi_email","domain":"chi-mail-machine","class_name":"CHI_EMAIL_SENDER","post-type":["post"],"context":"normal","priority":"low","cpt":"chi_email","fields":[{"type":"date","label":"Date the email was sent","id":"chi_emaildate-the-email-was-sent"},{"type":"time","label":"Time the email was sent","id":"chi_emailtime-the-email-was-sent"},{"type":"email","label":"For","id":"chi_emailfor"},{"type":"text","label":"Email Subject","id":"chi_emailemail-subject"},{"type":"textarea","label":" Notes on the text","id":"chi_emailnotes-on-the-text"}]}';

		public function __construct() {
			$this->config = json_decode( $this->config, true );
			$this->process_cpts();
			add_action( 'add_meta_boxes', [ $this, 'add_meta_boxes' ] );
			add_action( 'admin_head', [ $this, 'admin_head' ] );
			add_action( 'save_post', [ $this, 'save_post' ] );
		}

		public function process_cpts() {
			if ( ! empty( $this->config['cpt'] ) ) {
				if ( empty( $this->config['post-type'] ) ) {
					$this->config['post-type'] = [];
				}
				$parts                     = explode( ',', $this->config['cpt'] );
				$parts                     = array_map( 'trim', $parts );
				$this->config['post-type'] = array_merge( $this->config['post-type'], $parts );
			}
		}

		public function add_meta_boxes() {
			foreach ( $this->config['post-type'] as $screen ) {
				add_meta_box(
						sanitize_title( $this->config['title'] ),
						$this->config['title'],
						[ $this, 'add_meta_box_callback' ],
						$screen,
						$this->config['context'],
						$this->config['priority']
				);
			}
		}

		public function admin_head() {
			global $typenow;
			if ( in_array( $typenow, $this->config['post-type'] ) ) {
				?><?php
			}
		}

		public function save_post( $post_id ) {

			// Stop WP from clearing custom fields on autosave
			if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
				return;
			}

			// Prevent quick edit from clearing custom fields
			if ( defined( 'DOING_AJAX' ) && DOING_AJAX ) {
				return;
			}

			if ( isset( $_POST['chi_emailchoose-option'] ) ) {

				if ( $_POST['chi_emailchoose-option'] == '1' ) {

					foreach ( $this->config['fields'] as $field ) {


						$sanitized = sanitize_text_field( $_POST[ $field['id'] ] );

						switch ( $field['id'] ) {
							case 'chi_emailnotes-on-the-text':

								if ( isset( $_POST[ $field['id'] ] ) ) {

									if ( empty( $_POST[ $field['id'] ] ) ) {
										break;
									}

									$author_id = get_current_user_id();

									$agent = $_SERVER['HTTP_USER_AGENT'];
									$data  = array(
											'comment_post_ID'      => $post_id,
											'comment_author'       => get_the_author_meta( 'nickname', $author_id ),
											'comment_author_email' => get_the_author_meta( 'user_email', $author_id ),
											'comment_content'      => $sanitized,
											'comment_author_IP'    => get_the_user_ip(),
											'comment_agent'        => $agent,
											'comment_date'         => date( 'Y-m-d H:i:s' ),
											'comment_date_gmt'     => date( 'Y-m-d H:i:s' ),
											'comment_approved'     => 1,
									);

									wp_insert_comment( $data );
								}
								break;
							default:
								$user = wp_get_current_user();
								if ( ! ( in_array( 'administrator', (array) $user->roles ) ) ) {
									break;
								}
								update_post_meta( $post_id, $field['id'], $sanitized );
								break;

						}
					}
				}
				if ( $_POST['chi_emailchoose-option'] == '2' ) {
					foreach ( $this->config['fields'] as $field ) {

						$sanitized = sanitize_text_field( $_POST[ $field['id'] ] );

						//RespiroNews - Newsletter č. 32R - rozesílka 8.4.2021 06:00
						//						Dobrý deň,
						//
						//						poprosil by som Vás o nastavenie emailu 32R pre projekt RespiroNews
						//						na zajtra tj. 8.4.2020 o 6h.
						//
						//						Predmet: Plicní embolie při COVID-19 – co je pro ni charakteristické?
						//
						//						Za skorú odpoveď
						//						Ďakujem

						if ( isset( $_POST['chi_email_taxonomy_select'] ) &&
							 isset( $_POST['chi_email_special_number'] ) &&
							 isset( $_POST['chi_emailfor'] ) &&
							 isset( $_POST['chi_emailemail-subject'] ) &&
							 isset( $_POST['chi_emaildate-the-email-was-sent'] ) &&
							 isset( $_POST['chi_emailtime-the-email-was-sent'] ) &&
							 isset( $_POST['chi_emailnotes-on-the-text'] ) ) {


							$subject_data = ucwords( $_POST['chi_email_taxonomy_select'] ) . ' - Newsletter č. ' . $_POST['chi_email_special_number'] . ' - rozesílka ' . $_POST['chi_emaildate-the-email-was-sent'] . ' ' . $_POST['chi_emailtime-the-email-was-sent'];

							$subject = sanitize_text_field( $subject_data );

							$message = nl2br( 'Dobrý deň,<br><br>Poprosil by som Vás o nastavenie emailu č. <strong>' . $_POST['chi_email_special_number'] . '</strong> pre projekt <strong>' . ucwords( $_POST['chi_email_taxonomy_select'] ) . '</strong> na <strong>' . $_POST['chi_emaildate-the-email-was-sent'] . '</strong> o <strong>' . $_POST['chi_emailtime-the-email-was-sent'] . '</strong>.<br><br>Predmet: <strong>' . get_the_title() . '</strong><br><br>Za skorú odpoveď<br>Ďakujem', true );

						}
						// chi_email_taxonomy_select
						// chi_email_special_number
						// chi_emailfor
						// chi_emailemail-subject
						// chi_emaildate-the-email-was-sent
						// chi_emailtime-the-email-was-sent
						// chi_emailnotes-on-the-text

						switch ( $field['id'] ) {
							case 'chi_emailnotes-on-the-text':
								if ( isset( $_POST[ $field['id'] ] ) ) {

									if ( ! empty( $_POST[ $field['id'] ] ) ) {
										break;
									}

									$author_id = get_current_user_id();

									$agent = $_SERVER['HTTP_USER_AGENT'];
									$data  = array(
											'comment_post_ID'      => $post_id,
											'comment_author'       => get_the_author_meta( 'nickname', $author_id ),
											'comment_author_email' => get_the_author_meta( 'user_email', $author_id ),
											'comment_content'      => $message,
											'comment_author_IP'    => get_the_user_ip(),
											'comment_agent'        => $agent,
											'comment_date'         => date( 'Y-m-d H:i:s' ),
											'comment_date_gmt'     => date( 'Y-m-d H:i:s' ),
											'comment_approved'     => 1,
									);

									$comment_id = wp_insert_comment( $data );
									add_comment_meta( $comment_id, 'subject', $subject );

								}
								break;
							default:
								$user = wp_get_current_user();
								if ( ! ( in_array( 'administrator', (array) $user->roles ) ) ) {
									break;
								}
								update_post_meta( $post_id, $field['id'], $sanitized );
								break;

						}
					}
				}
				if ( $_POST['chi_emailchoose-option'] == '3' ) {
					foreach ( $this->config['fields'] as $field ) {

						$sanitized = sanitize_text_field( $_POST[ $field['id'] ] );

						if ( isset( $_POST['chi_emailfor'] ) &&
							 isset( $_POST['chi_emailemail-subject'] ) &&
							 isset( $_POST['chi_emailnotes-on-the-text'] ) ) {


							$subject = sanitize_text_field( $_POST['chi_emailemail-subject'] );
							$message = sanitize_text_field( $_POST['chi_emailnotes-on-the-text'] );

						}

						switch ( $field['id'] ) {
							case 'chi_emailnotes-on-the-text':
								if ( isset( $_POST[ $field['id'] ] ) ) {

									if ( empty( $_POST[ $field['id'] ] ) ) {
										break;
									}

									$author_id = get_current_user_id();

									$agent = $_SERVER['HTTP_USER_AGENT'];
									$data  = array(
											'comment_post_ID'      => $post_id,
											'comment_author'       => get_the_author_meta( 'nickname', $author_id ),
											'comment_author_email' => get_the_author_meta( 'user_email', $author_id ),
											'comment_content'      => $message,
											'comment_author_IP'    => get_the_user_ip(),
											'comment_agent'        => $agent,
											'comment_date'         => date( 'Y-m-d H:i:s' ),
											'comment_date_gmt'     => date( 'Y-m-d H:i:s' ),
											'comment_approved'     => 1,
									);

									$comment_id = wp_insert_comment( $data );
									add_comment_meta( $comment_id, 'subject', $subject );

								}
								break;
							default:
								$user = wp_get_current_user();
								if ( ! ( in_array( 'administrator', (array) $user->roles ) ) ) {
									break;
								}
								update_post_meta( $post_id, $field['id'], $sanitized );
								break;

						}
					}
				}
			}
		}

		public function add_meta_box_callback() {
			echo '<div class="rwp-description">' . $this->config['description'] . '</div>';
			$this->fields_table();
		}

		private function fields_table() {
			$args     = array(
					'post_id' => get_the_ID(),   // Use post_id, not post_ID
			);
			$comments = get_comments( $args );

			?>
			<ul class="order_notes">
				<?php foreach ( $comments as $comment ) : ?>
					<li rel="<?php $comment->comment_ID; ?>" class="note">
						<div class="note_content <?php echo( get_comment_meta( $comment->comment_ID, 'subject', true ) ? 'note_content--info' : '' ) ?>">
							<?php if ( get_comment_meta( $comment->comment_ID, 'subject', true ) ) : ?>
								<p>Predmet emailu:
									<strong><?php echo get_comment_meta( $comment->comment_ID, 'subject', true ) ?></strong>
								</p>
							<?php endif ?>
							<p><?php echo $comment->comment_content; ?></p>
						</div>
						<p class="meta">
							<abbr class="exact-date" title="<?php echo $comment->comment_date_gmt ?>">
								<?php echo $comment->comment_date; ?></abbr>
							<?php echo $comment->comment_author; ?>
							<a href="<?php echo admin_url( '/comment.php?action=editcomment&c=' . $comment->comment_ID . '' ); ?>"
							   class="vim-q comment-inline button-link" role="button">Edit note</a> |
							<?php
								$del_nonce = esc_html( '_wpnonce=' . wp_create_nonce( "delete-comment_$comment->comment_ID" ) );
								$trash_url = $trash_url = esc_url( "comment.php?action=trashcomment&p=$comment->comment_post_ID&c=$comment->comment_ID&$del_nonce&reason=1" );
							?>
							<a href="<?php echo $trash_url ?>"
							   onclick="return confirm('Are you sure?')" class="delete_note" role="button">Delete
								note</a>
						</p>
					</li>
				<?php endforeach ?>
			</ul>
			<table class="form-table" role="presentation">
				<tbody><?php
					foreach ( $this->config['fields'] as $field ) {
						?>
					<tr class="tr-<?php echo $field['id'] ?>">
						<th scope="row"><?php $this->label( $field ); ?></th>
						<td><?php $this->field( $field ); ?></td>
						</tr><?php
					}
				?>
				<tr>
					<th scope="row">
						<label for="<?php echo $this->config['prefix'] ?>choose-option">Choose an option:</label>
					</th>
					<td>
						<select name="<?php echo $this->config['prefix'] ?>choose-option"
								id="<?php echo $this->config['prefix'] ?>choose-option">
							<option value="1">Email note</option>
							<?php if ( ( in_array( 'administrator', (array) wp_get_current_user()->roles ) ) ) : ?>
								<option value="2">Sending an email to an external company</option>
								<option value="3">Edit email</option>
							<?php endif ?>
						</select>
						<input id="publishComment" class="button-primary" type="submit" value="Send" accesskey="p"
							   tabindex="5"
							   name="Send">
						<span class="spinner"></span>
					</td>
				</tr>
				</tbody>
			</table>
			<script>
				(function ($) {
					console.log("ready");

					$('#publishComment').on('click', function (e) {
						e.preventDefault();
						console.log("click");
						$.post(
								ajaxurl,
								{
									'action': 'add_myfunc',
									'data': 'foobarid',
								},
								function (response) {

									console.log(response);
								}
						);
					});
				})(jQuery);
			</script>
			<?php
		}


		private function label( $field ) {
			switch ( $field['type'] ) {
				default:
					printf(
							'<label class="" for="%s">%s</label>',
							$field['id'], $field['label']
					);
			}
		}

		private function field( $field ) {
			switch ( $field['type'] ) {
				case 'date':
				case 'time':
					$this->input_minmax( $field );
					break;
				case 'textarea':
					$this->textarea( $field );
					break;
				default:
					$this->input( $field );
			}
		}

		private function input( $field ) {
			printf(
					'<input class="regular-text %s" id="%s" name="%s" %s type="%s" value="%s">',
					isset( $field['class'] ) ? $field['class'] : '',
					$field['id'], $field['id'],
					isset( $field['pattern'] ) ? "pattern='{$field['pattern']}'" : '',
					$field['type'],
					$this->value( $field )
			);
		}

		private function input_minmax( $field ) {
			printf(
					'<input class="regular-text" id="%s" %s %s name="%s" %s type="%s" value="%s">',
					$field['id'],
					isset( $field['max'] ) ? "max='{$field['max']}'" : '',
					isset( $field['min'] ) ? "min='{$field['min']}'" : '',
					$field['id'],
					isset( $field['step'] ) ? "step='{$field['step']}'" : '',
					$field['type'],
					$this->value( $field )
			);
		}

		private function textarea( $field ) {
			printf(
					'<textarea class="regular-text" id="%s" name="%s" rows="%d">%s</textarea>',
					$field['id'], $field['id'],
					isset( $field['rows'] ) ? $field['rows'] : 5,
					$this->value( $field )
			);
		}

		private function value( $field ) {
			global $post;
			if ( metadata_exists( 'post', $post->ID, $field['id'] ) ) {
				$value = get_post_meta( $post->ID, $field['id'], true );
			} else if ( isset( $field['default'] ) ) {
				$value = $field['default'];
			} else {
				return '';
			}

			return str_replace( '\u0027', "'", $value );
		}

		public function example_ajax_request() {
			// The $_REQUEST contains all the data sent via AJAX from the Javascript call
			if ( isset($_REQUEST) ) {

				$fruit = $_REQUEST['fruit'];

				// This bit is going to process our fruit variable into an Apple
				if ( $fruit == 'Banana' ) {
					$fruit = 'Apple';
				}

				// Now let's return the result to the Javascript function (The Callback)
				echo $fruit;
			}

			// Always die in functions echoing AJAX content
			die();
		}

	}


